#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write --allow-run
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
// Everything above STAGES is the wizard library: author only the stages below.

import { dirname } from "node:path";

export interface CommandResult {
  readonly code: number;
  readonly stdout: string;
}

export type Runner = (
  command: string,
  args: readonly string[],
  input?: string,
) => Promise<CommandResult | undefined>;

export const runCommand: Runner = async (command, args, input) => {
  try {
    const child = new Deno.Command(command, {
      args: [...args],
      stdin: input === undefined ? "inherit" : "piped",
      stdout: "piped",
      stderr: "null",
    }).spawn();
    if (input !== undefined) {
      try {
        const writer = child.stdin.getWriter();
        await writer.write(new TextEncoder().encode(input));
        await writer.close();
      } catch (error) {
        if (!(error instanceof Deno.errors.BrokenPipe)) throw error;
      }
    }
    const result = await child.output();
    return {
      code: result.code,
      stdout: new TextDecoder().decode(result.stdout),
    };
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
};

export class Interrupted extends Error {}

export interface InputSource {
  isTerminal(): boolean;
  setRaw(mode: boolean): void;
  read(buffer: Uint8Array): Promise<number | null>;
}

// Windows console reads need room for a complete UTF-8 character. Keep unread
// bytes between prompts so a larger read never discards later pasted lines.
export class LineReader {
  private readonly buffer = new Uint8Array(4096);
  private offset = 0;
  private length = 0;

  constructor(private readonly source: InputSource) {}

  private async nextByte(): Promise<number | null> {
    while (this.offset === this.length) {
      const length = await this.source.read(this.buffer);
      if (length === null) return null;
      this.offset = 0;
      this.length = length;
    }
    return this.buffer[this.offset++];
  }

  // Bash read -r ignores NUL and trims its default IFS (space and tab).
  async readLine(secret = false): Promise<string> {
    const terminal = this.source.isTerminal();
    const raw = secret && terminal;
    const bytes: number[] = [];
    if (raw) this.source.setRaw(true);
    try {
      let value: number | null;
      while ((value = await this.nextByte()) !== null) {
        if (value === 10 || (raw && value === 13)) {
          if (terminal && bytes.at(-1) === 13) bytes.pop();
          break;
        }
        if (raw && value === 3) throw new Interrupted();
        if (raw && value === 4) break;
        if (raw && (value === 127 || value === 8)) {
          while (bytes.length && (bytes[bytes.length - 1] & 0xc0) === 0x80) {
            bytes.pop();
          }
          bytes.pop();
        } else if (raw && value === 21) {
          bytes.length = 0;
        } else if (value !== 0) {
          bytes.push(value);
        }
      }
    } finally {
      if (raw) this.source.setRaw(false);
    }
    return new TextDecoder().decode(new Uint8Array(bytes)).replace(
      /^[ \t]+|[ \t]+$/g,
      "",
    );
  }
}

const stdinReader = new LineReader(Deno.stdin);

// Windows console byte reads follow the console input code page. Use UTF-8
// while reading and restore the caller's code page, including on interruption.
export async function readLine(secret = false): Promise<string> {
  if (Deno.build.os !== "windows" || !Deno.stdin.isTerminal()) {
    return await stdinReader.readLine(secret);
  }
  const codePage = (value?: number): string => {
    const result = new Deno.Command("chcp.com", {
      args: value === undefined ? [] : [String(value)],
      stdin: "null",
      stdout: "piped",
      stderr: "piped",
    }).outputSync();
    if (!result.success) {
      throw new Error("Could not configure the console input code page");
    }
    return new TextDecoder().decode(result.stdout);
  };
  const match = codePage().match(/(\d+)\D*$/);
  if (!match) {
    throw new Error("Could not determine the console input code page");
  }
  const original = Number(match[1]);
  if (original === 65001) return await stdinReader.readLine(secret);
  codePage(65001);
  let restored = false;
  const restore = () => {
    if (restored) return;
    codePage(original);
    restored = true;
  };
  const interrupt = () => {
    try {
      if (secret) Deno.stdin.setRaw(false);
      restore();
    } finally {
      Deno.exit(130);
    }
  };
  let listening = false;
  try {
    Deno.addSignalListener("SIGINT", interrupt);
    listening = true;
    return await stdinReader.readLine(secret);
  } finally {
    if (listening) Deno.removeSignalListener("SIGINT", interrupt);
    restore();
  }
}

export interface WizardOptions {
  readonly envFile?: string;
  readonly terminal?: boolean;
  readonly write?: (text: string) => void;
  readonly read?: (secret: boolean) => Promise<string>;
  readonly run?: Runner;
}

export class Wizard {
  totalStages = 0;
  stageIndex = 0;
  readonly writtenEnv: string[] = [];
  readonly writtenSecret: string[] = [];
  readonly skipped: string[] = [];
  readonly envFile: string;
  private readonly terminal: boolean;
  private readonly write: (text: string) => void;
  private readonly read: (secret: boolean) => Promise<string>;
  private readonly run: Runner;
  private bold = "";
  private dim = "";
  private reset = "";
  private blue = "";
  private green = "";
  private yellow = "";

  private constructor(options: WizardOptions) {
    this.envFile = options.envFile ?? (Deno.env.get("ENV_FILE") || ".env");
    this.terminal = options.terminal ?? Deno.stdout.isTerminal();
    this.write = options.write ?? ((text) => {
      const bytes = new TextEncoder().encode(text);
      let offset = 0;
      while (offset < bytes.length) {
        offset += Deno.stdout.writeSync(bytes.subarray(offset));
      }
    });
    this.read = options.read ?? readLine;
    this.run = options.run ?? runCommand;
  }

  static async create(options: WizardOptions = {}): Promise<Wizard> {
    const wizard = new Wizard(options);
    if (wizard.terminal) {
      const colors = await wizard.run("tput", ["colors"]);
      if (colors?.code === 0 && Number(colors.stdout.trim()) >= 8) {
        for (
          const [field, args] of [
            ["bold", ["bold"]],
            ["dim", ["dim"]],
            ["reset", ["sgr0"]],
            ["blue", ["setaf", "4"]],
            ["green", ["setaf", "2"]],
            ["yellow", ["setaf", "3"]],
          ] as const
        ) {
          const result = await wizard.run("tput", args);
          if (!result || result.code !== 0) throw new Error("tput failed");
          wizard[field] = result.stdout.replace(/\n+$/, "");
        }
      }
    }
    return wizard;
  }

  private async clear(): Promise<void> {
    if (!this.terminal) return;
    const result = await this.run("tput", ["clear"]);
    if (!result) this.write("\x1b[2J\x1b[3J\x1b[H");
    else {
      this.write(result.stdout);
      if (result.code !== 0) throw new Error("tput clear failed");
    }
  }

  async banner(title: string): Promise<void> {
    await this.clear();
    this.write(`\n${this.bold}${this.blue}  ${title}${this.reset}\n`);
    this.write(`${this.dim}  ${this.totalStages} stages${this.reset}\n\n`);
    this.write(
      `${this.dim}  You drive the browser; this wizard tells you exactly what to do and\n`,
    );
    this.write(
      "  captures the values you copy back. Stop any time with Ctrl-C and re-run\n",
    );
    this.write(
      `  later, since it remembers values already saved.${this.reset}\n`,
    );
    await this.pause("Ready to start?");
  }

  async stage(name: string): Promise<void> {
    await this.clear();
    this.stageIndex++;
    this.write(
      `\n${this.bold}${this.blue}▸ Stage ${this.stageIndex}/${this.totalStages} · ${name}${this.reset}\n`,
    );
  }

  say(text: string): void {
    this.write(`  ${text}\n`);
  }
  step(text: string): void {
    this.write(`  ${this.blue}•${this.reset} ${text}\n`);
  }
  note(text: string): void {
    this.write(`  ${this.dim}${text}${this.reset}\n`);
  }
  warn(text: string): void {
    this.write(`  ${this.yellow}⚠ ${text}${this.reset}\n`);
  }

  async openUrl(url: string): Promise<void> {
    this.write(`  ${this.green}↗ opening${this.reset} ${url}\n`);
    for (const command of ["wslview", "explorer.exe", "xdg-open", "open"]) {
      const result = await this.run(command, [url]);
      if (!result) continue;
      if (result.code !== 0) {
        this.warn(`couldn't open a browser, so visit it manually: ${url}`);
      }
      return;
    }
    // The shell template redirects its missing-opener warning to /dev/null.
  }

  async pause(message = "Press Enter to continue"): Promise<void> {
    this.write(
      `  ${this.dim}${message || "Press Enter to continue"}${this.reset} `,
    );
    await this.read(false);
  }

  async confirm(question: string): Promise<boolean> {
    this.write(`  ${this.yellow}? ${question} [y/N] `);
    return /^[Yy]/.test(await this.read(false));
  }

  async existing(key: string): Promise<string> {
    try {
      if (!(await Deno.stat(this.envFile)).isFile) return "";
      const lines = (await Deno.readTextFile(this.envFile)).split("\n");
      const match = lines.filter((line) => new RegExp(`^${key}=`).test(line))
        .at(-1);
      return match?.slice(match.indexOf("=") + 1).replaceAll("\0", "") ?? "";
    } catch (error) {
      if (error instanceof Deno.errors.NotFound) return "";
      throw error;
    }
  }

  async ask(key: string, prompt: string, secret = false): Promise<string> {
    const current = await this.existing(key);
    this.write(`  ${this.bold}${prompt}${this.reset} `);
    if (current) this.write(`${this.dim}[Enter keeps current]${this.reset} `);
    const input = await this.read(secret);
    if (secret) this.write("\n");
    return input || current;
  }

  askSecret(key: string, prompt: string): Promise<string> {
    return this.ask(key, prompt, true);
  }

  async writeEnv(key: string, value: string): Promise<void> {
    // touch creates the target before grep; a temporary file gives the result
    // mktemp's private permissions on POSIX, just as the shell template does.
    const target = await Deno.open(this.envFile, {
      create: true,
      append: true,
    });
    target.close();
    const input = await Deno.readFile(this.envFile);
    const output = upsertEnv(input, key, value);
    const temporary = await Deno.makeTempFile({ dir: dirname(this.envFile) });
    await Deno.writeFile(temporary, output);
    await Deno.rename(temporary, this.envFile);
    this.writtenEnv.push(key);
    this.write(
      `  ${this.green}✓ wrote${this.reset} ${key} → ${this.envFile}\n`,
    );
  }

  async setSecret(name: string, value: string): Promise<void> {
    if (
      (await this.run("gh", ["auth", "status"]))?.code === 0 &&
      (await this.run("gh", ["secret", "set", name], value))?.code === 0
    ) {
      this.writtenSecret.push(name);
      this.write(`  ${this.green}✓ set${this.reset} GitHub secret ${name}\n`);
      return;
    }
    this.skipped.push(
      `GitHub secret ${name} (set it manually: gh secret set ${name})`,
    );
    this.warn(`skipped GitHub secret ${name}: gh not ready; set it later`);
  }

  async setVar(name: string, value: string): Promise<void> {
    if (
      (await this.run("gh", ["auth", "status"]))?.code === 0 &&
      (await this.run("gh", ["variable", "set", name, "--body", value]))
          ?.code === 0
    ) {
      this.write(`  ${this.green}✓ set${this.reset} GitHub variable ${name}\n`);
      return;
    }
    this.skipped.push(`GitHub variable ${name}`);
    this.warn(`skipped GitHub variable ${name}, gh not ready; set it later`);
  }

  async finish(): Promise<void> {
    await this.clear();
    this.write(`\n${this.bold}${this.green}  ✓ Setup complete${this.reset}\n`);
    if (this.writtenEnv.length) {
      this.note(
        `wrote ${this.writtenEnv.length} value(s) to ${this.envFile}: ${
          this.writtenEnv.join(" ")
        }`,
      );
    }
    if (this.writtenSecret.length) {
      this.note(
        `set ${this.writtenSecret.length} GitHub secret(s): ${
          this.writtenSecret.join(" ")
        }`,
      );
    }
    if (this.skipped.length) {
      this.write("\n");
      this.warn("still to do by hand:");
      for (const skipped of this.skipped) this.note(`  - ${skipped}`);
    }
    this.write("\n");
  }
}

// Keep unrelated line bytes, including CR, and add grep's final LF when absent.
export function upsertEnv(
  input: Uint8Array,
  key: string,
  value: string,
): Uint8Array {
  const chunks: Uint8Array[] = [];
  const pattern = new RegExp(`^${key}=`);
  const decoder = new TextDecoder();
  let start = 0;
  for (let end = 0; end <= input.length; end++) {
    if (end !== input.length && input[end] !== 10) continue;
    if (end > start || end < input.length) {
      const line = input.subarray(start, end);
      if (!pattern.test(decoder.decode(line))) {
        chunks.push(line, new Uint8Array([10]));
      }
    }
    start = end + 1;
  }
  chunks.push(new TextEncoder().encode(`${key}=${value}\n`));
  const output = new Uint8Array(
    chunks.reduce((length, chunk) => length + chunk.length, 0),
  );
  let offset = 0;
  for (const chunk of chunks) {
    output.set(chunk, offset);
    offset += chunk.length;
  }
  return output;
}

// STAGES: author this section. One stage() per step the human takes.
// Replace the example below. Set totalStages to match the stages you write.
export async function main(): Promise<void> {
  const wizard = await Wizard.create();
  wizard.totalStages = 1;
  await wizard.banner("Stripe setup");
  await wizard.stage("Stripe: API keys");
  wizard.say(
    "We'll grab your Stripe test keys and store them for local dev + CI.",
  );
  await wizard.openUrl("https://dashboard.stripe.com/test/apikeys");
  wizard.step(
    "On the API keys page, copy the Publishable key (starts pk_test_).",
  );
  const publishableKey = await wizard.ask(
    "STRIPE_PUBLISHABLE_KEY",
    "Paste the publishable key:",
  );
  wizard.step("Click 'Reveal test key' on the Secret key row, then copy it.");
  const secretKey = await wizard.askSecret(
    "STRIPE_SECRET_KEY",
    "Paste the secret key:",
  );
  await wizard.writeEnv("STRIPE_PUBLISHABLE_KEY", publishableKey);
  await wizard.writeEnv("STRIPE_SECRET_KEY", secretKey);
  await wizard.setSecret("STRIPE_SECRET_KEY", secretKey);
  await wizard.finish();
}

if (import.meta.main) {
  try {
    await main();
  } catch (error) {
    if (error instanceof Interrupted) Deno.exit(130);
    console.error(error instanceof Error ? error.message : String(error));
    Deno.exit(1);
  }
}
